export const IMAGES: { [key: string]: string } = {
    JacobIMG: './JacobIMG.jpg',
    badge: './Achievements/badge.png',
    img1: './Achievements/img1.png',
    img2: './Achievements/img2.png',
    img3: './Achievements/img3.png',
    pointsIcon: './Achievements/pointsIcon.png',
    home1: './Listing/home1.jpg',
    home2: './Listing/home2.jpg',
    home3: './Listing/home3.jpg',
    closed: './Listing/closed.png',
    'bell-icon': './Icons/bell.svg',
    user:'./Icons/user.svg',
    'down-arrow': './Icons/down-arrow.svg',
    facebook: './Icons/facebook.svg',
    youtube: './Icons/youtube.svg',
    linkedin: './Icons/linkedin.svg',
    phone: './Icons/phone.svg',
    instagram: './Icons/insta.svg',
    share: './Icons/share.svg',
    heart: './Icons/heart.svg',
    search:'./Icons/search.svg',
    location: './Icons/location.svg',
    camera: './Icons/camera.svg',
    bed: './Icons/bed.svg',
    shower:'./Icons/shower.svg',
    garage: './Icons/garage.svg',
    message: './Icons/message.svg',
    'filled-heart': './Icons/filled-heart.svg',
    twitter: './Icons/twitter.svg'
}